-- Sentinel AML - Core Data Model & Ingestion Layer
-- Customer -> Account -> Transaction, plus Alert / Case and ingestion/audit support.

CREATE TABLE IF NOT EXISTS customers (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id              VARCHAR(64)  NOT NULL UNIQUE,
    first_name               VARCHAR(100) NOT NULL,
    last_name                VARCHAR(100) NOT NULL,
    gender                   VARCHAR(20),
    date_of_birth            DATE,
    email                    VARCHAR(255),
    phone_number             VARCHAR(50),
    city                     VARCHAR(100),
    state                    VARCHAR(100),
    country                  VARCHAR(3),
    postal_code              VARCHAR(20),
    occupation               VARCHAR(150),
    annual_income            NUMERIC(19, 2),
    marital_status           VARCHAR(30),
    education_level          VARCHAR(50),
    employment_status        VARCHAR(30),
    customer_since           DATE,
    customer_segment         VARCHAR(30),
    kyc_status               VARCHAR(30),
    risk_rating              VARCHAR(20) NOT NULL DEFAULT 'LOW',
    is_politically_exposed   BOOLEAN      NOT NULL DEFAULT FALSE,
    preferred_channel        VARCHAR(50),
    email_verified           BOOLEAN      NOT NULL DEFAULT FALSE,
    phone_verified           BOOLEAN      NOT NULL DEFAULT FALSE,
    num_complaints_last_year INTEGER      NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_customers_risk_rating ON customers (risk_rating);
CREATE INDEX IF NOT EXISTS idx_customers_country     ON customers (country);

CREATE TABLE IF NOT EXISTS accounts (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id               VARCHAR(64) NOT NULL UNIQUE,
    customer_id              BIGINT      NOT NULL REFERENCES customers (id) ON DELETE RESTRICT,
    account_type             VARCHAR(30),
    account_status           VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    currency                 VARCHAR(3)  NOT NULL DEFAULT 'INR',
    open_date                DATE,
    close_date               DATE,
    branch_code              VARCHAR(30),
    branch_city              VARCHAR(100),
    current_balance          NUMERIC(19, 2),
    avg_monthly_balance_6m   NUMERIC(19, 2),
    credit_limit             NUMERIC(19, 2),
    credit_utilization_pct   NUMERIC(7, 4),
    overdraft_enabled        BOOLEAN     NOT NULL DEFAULT FALSE,
    card_type                VARCHAR(30),
    is_joint_account         BOOLEAN     NOT NULL DEFAULT FALSE,
    num_linked_devices       INTEGER     NOT NULL DEFAULT 0,
    mobile_banking_enrolled  BOOLEAN     NOT NULL DEFAULT FALSE,
    last_login_date          DATE,
    avg_monthly_txn_count    INTEGER,
    account_tier             VARCHAR(30),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_accounts_customer_id ON accounts (customer_id);
CREATE INDEX IF NOT EXISTS idx_accounts_status      ON accounts (account_status);

CREATE TABLE IF NOT EXISTS transactions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_ref       VARCHAR(100)  NOT NULL UNIQUE,
    account_id            BIGINT        NOT NULL REFERENCES accounts (id) ON DELETE RESTRICT,
    amount                NUMERIC(19, 2) NOT NULL,
    currency              VARCHAR(3)    NOT NULL,
    amount_base           NUMERIC(19, 2),
    base_currency         VARCHAR(3),
    transaction_type      VARCHAR(30),
    direction             VARCHAR(10),
    counterparty_name     VARCHAR(255),
    counterparty_account  VARCHAR(100),
    counterparty_country  VARCHAR(3),
    channel               VARCHAR(50),
    jurisdiction          VARCHAR(3),
    description           VARCHAR(500),
    transaction_time      TIMESTAMPTZ   NOT NULL,
    ingestion_source      VARCHAR(20)   NOT NULL DEFAULT 'API',
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_transactions_account_time  ON transactions (account_id, transaction_time);
CREATE INDEX IF NOT EXISTS idx_transactions_time          ON transactions (transaction_time);
CREATE INDEX IF NOT EXISTS idx_transactions_cpty_country  ON transactions (counterparty_country);
CREATE INDEX IF NOT EXISTS idx_transactions_jurisdiction  ON transactions (jurisdiction);

CREATE TABLE IF NOT EXISTS alerts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_ref     VARCHAR(64)  NOT NULL UNIQUE,
    customer_id   BIGINT       REFERENCES customers (id) ON DELETE RESTRICT,
    account_id    BIGINT       REFERENCES accounts (id) ON DELETE SET NULL,
    rule_code     VARCHAR(64)  NOT NULL,
    title         VARCHAR(255),
    explanation   TEXT,
    risk_score    INTEGER      NOT NULL DEFAULT 0,
    severity      VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',
    status        VARCHAR(30)  NOT NULL DEFAULT 'OPEN',
    dedup_key     VARCHAR(255),
    assigned_to   VARCHAR(100),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_alerts_customer ON alerts (customer_id);
CREATE INDEX IF NOT EXISTS idx_alerts_status   ON alerts (status);
CREATE INDEX IF NOT EXISTS idx_alerts_dedup    ON alerts (dedup_key);

CREATE TABLE IF NOT EXISTS alert_transactions (
    alert_id       BIGINT NOT NULL REFERENCES alerts (id) ON DELETE CASCADE,
    transaction_id BIGINT NOT NULL REFERENCES transactions (id) ON DELETE RESTRICT,
    PRIMARY KEY (alert_id, transaction_id)
);

CREATE TABLE IF NOT EXISTS cases (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_ref           VARCHAR(64) NOT NULL UNIQUE,
    customer_id        BIGINT      REFERENCES customers (id) ON DELETE RESTRICT,
    title              VARCHAR(255) NOT NULL,
    description        TEXT,
    status             VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    priority           VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    assigned_to        VARCHAR(100),
    disposition        VARCHAR(50),
    disposition_reason TEXT,
    opened_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at          TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cases_customer ON cases (customer_id);
CREATE INDEX IF NOT EXISTS idx_cases_status   ON cases (status);

CREATE TABLE IF NOT EXISTS case_alerts (
    case_id  BIGINT NOT NULL REFERENCES cases (id) ON DELETE CASCADE,
    alert_id BIGINT NOT NULL REFERENCES alerts (id) ON DELETE RESTRICT,
    PRIMARY KEY (case_id, alert_id)
);

CREATE TABLE IF NOT EXISTS ingestion_errors (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id         VARCHAR(64),
    entity_type      VARCHAR(30)  NOT NULL,
    source_name      VARCHAR(255),
    source_reference VARCHAR(255),
    raw_record       TEXT,
    error_type       VARCHAR(40)  NOT NULL,
    error_message    VARCHAR(1000) NOT NULL,
    occurred_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ingestion_errors_batch ON ingestion_errors (batch_id);

CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(30)  NOT NULL,
    entity_ref  VARCHAR(100) NOT NULL,
    action      VARCHAR(50)  NOT NULL,
    from_state  VARCHAR(50),
    to_state    VARCHAR(50),
    actor       VARCHAR(100) NOT NULL,
    details     TEXT,
    occurred_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_log_entity ON audit_log (entity_type, entity_ref);

CREATE TABLE IF NOT EXISTS exchange_rates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_currency VARCHAR(3)    NOT NULL,
    to_currency   VARCHAR(3)    NOT NULL,
    rate          NUMERIC(19, 8) NOT NULL,
    effective_from TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (from_currency, to_currency, effective_from)
);

CREATE INDEX IF NOT EXISTS idx_exchange_rates_pair ON exchange_rates (from_currency, to_currency);
