-- V5__detection_engine.sql
-- Configurable rule settings + high-risk jurisdictions for the Detection Engine (Part B).
-- Rules are toggled/tuned at runtime via the admin API or SQL -- no code redeployment.

CREATE TABLE IF NOT EXISTS rule_config (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code     VARCHAR(50)  NOT NULL UNIQUE,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    configuration TEXT         NOT NULL DEFAULT '{}',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rule_config_code ON rule_config (rule_code);

CREATE TABLE IF NOT EXISTS high_risk_jurisdictions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code   VARCHAR(3)  NOT NULL,
    description    VARCHAR(255),
    is_sanctioned  BOOLEAN     NOT NULL DEFAULT FALSE,
    effective_from TIMESTAMPTZ NOT NULL DEFAULT now(),
    effective_to   TIMESTAMPTZ,
    UNIQUE (country_code, effective_from)
);

CREATE INDEX IF NOT EXISTS idx_hrj_country ON high_risk_jurisdictions (country_code);

-- Alerts now carry the aggregated set of triggered rule codes plus audit disposition data.
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS triggered_rules TEXT;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS disposition VARCHAR(50);
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS disposition_reason TEXT;

-- Seed default rule configuration.
-- NOTE: thresholds are expressed in the configured base currency (sentinel.base-currency, INR by
-- default). The business rule "$10,000 / $9,000-$9,999" maps to these figures after currency
-- normalisation; production can raise them (e.g. 832500.00 for a USD 10k equivalent at 83.25).
INSERT INTO rule_config (rule_code, enabled, configuration) VALUES
    ('CTR', TRUE, '{"threshold_amount": 10000.00, "score": 20, "currency": "INR"}'),
    ('STRUCTURING', TRUE, '{"threshold_lower": 9000.00, "threshold_upper": 9999.00, "window_hours": 24, "min_transactions": 3, "score": 30}'),
    ('RAPID_MOVEMENT', TRUE, '{"transfer_pct": 0.80, "window_hours": 48, "score": 25}'),
    ('HIGH_RISK_JURISDICTION', TRUE, '{"score": 40}'),
    ('BEHAVIORAL_DEVIATION', TRUE, '{"multiplier": 3.0, "rolling_days": 90, "min_avg_base": 1.0, "score": 20}'),
    ('ROUND_NUMBER', TRUE, '{"round_interval": 1000.00, "min_transactions": 3, "window_hours": 24, "score": 10}')
ON CONFLICT (rule_code) DO NOTHING;

-- Seed a configurable high-risk / sanctions list (FATF high-risk & monitored jurisdictions).
INSERT INTO high_risk_jurisdictions (country_code, description, is_sanctioned) VALUES
    ('AF', 'Afghanistan', TRUE),
    ('BY', 'Belarus', TRUE),
    ('MM', 'Myanmar', TRUE),
    ('KP', 'North Korea', TRUE),
    ('IR', 'Iran', TRUE),
    ('RU', 'Russia', TRUE),
    ('SY', 'Syria', TRUE),
    ('VE', 'Venezuela', FALSE),
    ('YE', 'Yemen', FALSE)
ON CONFLICT (country_code, effective_from) DO NOTHING;